// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0PkOgWgyLPwA3HhU__SOILkMJ0MVpMlY',
    appId: '1:673438020148:web:b6a6b71bc81f98077e1061',
    messagingSenderId: '673438020148',
    projectId: 'fetansuki',
    authDomain: 'fetansuki.firebaseapp.com',
    storageBucket: 'fetansuki.firebasestorage.app',
    measurementId: 'G-26PPX6CB6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZN52knd4eAeQBbHR0mh3DYy9UhahMC0',
    appId: '1:673438020148:android:58f81d3583558cc57e1061',
    messagingSenderId: '673438020148',
    projectId: 'fetansuki',
    storageBucket: 'fetansuki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFuDtEJVhIscNtMY_6ooqoBBac1Wyt5dc',
    appId: '1:673438020148:ios:24d76d31aa1b572d7e1061',
    messagingSenderId: '673438020148',
    projectId: 'fetansuki',
    storageBucket: 'fetansuki.firebasestorage.app',
    iosBundleId: 'com.example.fetansukiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFuDtEJVhIscNtMY_6ooqoBBac1Wyt5dc',
    appId: '1:673438020148:ios:24d76d31aa1b572d7e1061',
    messagingSenderId: '673438020148',
    projectId: 'fetansuki',
    storageBucket: 'fetansuki.firebasestorage.app',
    iosBundleId: 'com.example.fetansukiApp',
  );
}
